### ISSUE TITLE
audio slicer get a error : [ERROR] libsndfile error 1: Format not recognised.

### ISSUE THREAD

**Issue by dxinli** [openvpi/dataset-tools#4]
audio slicer get a error . 
env: win11 
andio duraoin : 40 minute

**Comment by yqzhishen** [comment]
Do you mind uploading your audio file here?

**Comment by dxinli** [comment]
file is larger,upload failed

**Comment by yqzhishen** [comment]
Use a cloud drive or anything you would like

**Comment by dxinli** [comment]
google driver, link: https://drive.google.com/file/d/1NLtWuDjA1VAr37uVhHQPbTq5PRIK2n2H/view?usp=sharing

**Comment by yqzhishen** [comment]
Your file is actually in AAC format, not WAV. RENAMING the suffix does not mean you CONVERTED the file format. Audio slicer recognize the WAV format, not the ".wav" suffix.

**Comment by dxinli** [comment]
ok , thank you
